# Generated by Django 2.2.1 on 2019-08-08 07:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('staff_id', models.CharField(max_length=32, verbose_name='工号')),
                ('department', models.CharField(max_length=16, verbose_name='部门')),
                ('position', models.CharField(max_length=16, verbose_name='职位')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=16, verbose_name='电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='客户编码')),
                ('client_name', models.CharField(max_length=128, verbose_name='客户名称')),
                ('user_name', models.CharField(max_length=128, verbose_name='使用客户')),
                ('standard_address', models.CharField(max_length=256, verbose_name='标准地址')),
                ('client_address', models.CharField(max_length=256, verbose_name='客户地址')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='专线号')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, '正常'), (1, '拆机'), (2, '单停'), (3, '双停'), (4, '停机保号'), (5, '其他')], default=0, verbose_name='状态')),
                ('MKT_CHNL_NAME', models.CharField(max_length=128)),
                ('MKT_GRID_NAME', models.CharField(max_length=128)),
                ('receive_org', models.CharField(max_length=128, verbose_name='揽收组织')),
                ('PRODUCT_NAME', models.CharField(max_length=128)),
                ('main_set', models.CharField(max_length=256, verbose_name='主套餐')),
                ('add_set', models.CharField(max_length=256, verbose_name='加装包')),
                ('CRM', models.CharField(max_length=32)),
                ('product_quality', models.CharField(max_length=64, verbose_name='产品性质')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.IntegerField(verbose_name='套餐带宽')),
                ('true_bandwidth', models.IntegerField(verbose_name='实际带宽')),
                ('net_management', models.CharField(max_length=16, verbose_name='集团网管监控')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.FloatField(verbose_name='合同金额')),
                ('contract_id', models.CharField(max_length=32, verbose_name='合同编码')),
                ('contract_date', models.DateField(verbose_name='合同签订时间')),
                ('contract_expire', models.DateField(verbose_name='合同到期时间')),
                ('allowance', models.FloatField(verbose_name='交叉补贴')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Product')),
            ],
        ),
    ]
